### ISSUE TITLE
Request for documentation

### ISSUE THREAD

**Issue by ghost** [tnelson/FlowLog#49]
Hi, is any documentation available for FlowLog? I'm using the VM and trying to make sense of what's going in in the sample scripts, but was hoping that there might be some formal doc available.

**Comment by tnelson** [comment]
There are a few sources for documentation. The primary reference is our NSDI paper:
http://web.cs.wpi.edu/~tn/publications/nfsk-flowlog-nsdi14.pdf

but we've done quite a bit of new development since then. We have supplementary docs that haven't been formally released. I put these up on a temporary site:

http://cs.brown.edu/~tn/temp/flowlog-site/getting-started/
http://cs.brown.edu/~tn/temp/flowlog-site/flowlog-lang/

Hope those help!

**Comment by roney-michael** [comment]
Thanks a lot!
